config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :departments
  resources :payments
  resources :faculties
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  belongs_to :user
  has_one  :department, dependent: :destroy
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:faculty_name, :facult_code, :user_id)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
        <% faculty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :faculty_name %>
    <%= form.text_field :faculty_name %>
  </div>

  <div class="field">
    <%= form.label :facult_code %>
    <%= form.text_field :facult_code %>
  </div>

  <div class="field">
  <%= form.collection_select(:user_id, User.all, :id, :first_name, {}, { :multiple =>false} ) %>    
  </div>

  <div class="actions">
    <%= form.submit 'Save' %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty, class: 'btn btn-light' %> 
<%= link_to 'Back', faculties_path , class: 'btn btn-light' %>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faculties</h1>

<table>
  <thead>
    <tr>
      <th>Faculty name</th>
      <th>Facult code</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.faculty_name %></td>
        <td><%= faculty.facult_code %></td>
        <td><%= faculty.user.last_name %></td>
        <td><%= link_to 'Show', faculty, class: 'btn btn-info btn btn-sm' %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty), class: 'btn btn-success btn btn-sm' %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_faculty_path, class: 'btn btn-light' %>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path, class: 'btn btn-light' %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Faculty name:</strong>
  <%= @faculty.faculty_name %>
</p>

<p>
  <strong>Facult code:</strong>
  <%= @faculty.facult_code %>
</p>

<p>
  <strong>User:</strong>
  <%= @faculty.user.last_name %>
</p>

<%= link_to 'Edit', edit_faculty_path(@faculty), class: 'btn btn-light' %>
<%= link_to 'Back', faculties_path, class: 'btn btn-light' %>